### ISSUE TITLE
There is something wrong with LongImageActivity

### ISSUE THREAD

**Issue by r17171709** [Piasy/BigImageViewer#125]
``` 
java.lang.RuntimeException: onFailureImpl
W/System.err:     at com.github.piasy.biv.loader.fresco.ImageDownloadSubscriber.onFailureImpl(ImageDownloadSubscriber.java:88)
W/System.err:     at com.facebook.datasource.BaseDataSubscriber.onFailure(BaseDataSubscriber.java:57)
W/System.err:     at com.facebook.datasource.AbstractDataSource$1.run(AbstractDataSource.java:172)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/System.err:     at com.facebook.imagepipeline.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:51)
W/System.err:     at java.lang.Thread.run(Thread.java:764)
```

**Comment by Piasy** [comment]
It's just a loading failure, maybe network error, or something else.
