### ISSUE TITLE
Can not display mThumbnailView and mProgressIndicator

### ISSUE THREAD

**Issue by nukc** [Piasy/BigImageViewer#129]
When use showImage(final Uri thumbnail, final Uri uri); thumbnail is not Uri.EMPTY, then in
https://github.com/Piasy/BigImageViewer/blob/master/BigImageViewer/src/main/java/com/github/piasy/biv/view/BigImageView.java#L389-L390
```java
2018-10-22 14:17:24.065 22736-22736/  W/System.err: java.lang.reflect.InvocationTargetException
2018-10-22 14:17:24.066 22736-22736/  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-10-22 14:17:24.066 22736-22736/  W/System.err:     at com.github.piasy.biv.utils.ThreadedCallbacks$1.run(ThreadedCallbacks.java:74)
2018-10-22 14:17:24.067 22736-22736/  W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2018-10-22 14:17:24.067 22736-22736/  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2018-10-22 14:17:24.068 22736-22736/  W/System.err:     at android.os.Looper.loop(Looper.java:154)
2018-10-22 14:17:24.068 22736-22736/  W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6348)
2018-10-22 14:17:24.069 22736-22736/  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-10-22 14:17:24.069 22736-22736/  W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:920)
2018-10-22 14:17:24.070 22736-22736/  W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
2018-10-22 14:17:24.071 22736-22736/  W/System.err: Caused by: java.lang.NullPointerException
2018-10-22 14:17:24.071 22736-22736/  W/System.err:     at android.widget.ImageView.setScaleType(ImageView.java:737)
2018-10-22 14:17:24.072 22736-22736/  W/System.err:     at com.github.piasy.biv.view.GlideImageViewFactory.createThumbnailView(GlideImageViewFactory.java:65)
2018-10-22 14:17:24.072 22736-22736/  W/System.err:     at com.github.piasy.biv.view.BigImageView.onStart(BigImageView.java:389)
2018-10-22 14:17:24.073 22736-22736/  W/System.err: 	... 9 more
2018-10-22 14:17:24.075 22736-22736/  W/System.err: java.lang.reflect.InvocationTargetException
2018-10-22 14:17:24.075 22736-22736/  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-10-22 14:17:24.076 22736-22736/  W/System.err:     at com.github.piasy.biv.utils.ThreadedCallbacks$1.run(ThreadedCallbacks.java:74)
2018-10-22 14:17:24.076 22736-22736/  W/System.err:     at android.os.Handler.handleCallback(Handler.java:751)
2018-10-22 14:17:24.077 22736-22736/  W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2018-10-22 14:17:24.077 22736-22736/  W/System.err:     at android.os.Looper.loop(Looper.java:154)
2018-10-22 14:17:24.078 22736-22736/  W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6348)
2018-10-22 14:17:24.078 22736-22736/  W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2018-10-22 14:17:24.079 22736-22736/  W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:920)
2018-10-22 14:17:24.079 22736-22736/  W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)
2018-10-22 14:17:24.080 22736-22736/  W/System.err: Caused by: java.lang.NullPointerException
2018-10-22 14:17:24.081 22736-22736/  W/System.err:     at android.widget.ImageView.setScaleType(ImageView.java:737)
2018-10-22 14:17:24.081 22736-22736/  W/System.err:     at com.github.piasy.biv.view.GlideImageViewFactory.createThumbnailView(GlideImageViewFactory.java:65)
2018-10-22 14:17:24.082 22736-22736/  W/System.err:     at com.github.piasy.biv.view.BigImageView.onStart(BigImageView.java:389)
2018-10-22 14:17:24.082 22736-22736/  W/System.err: 	... 9 more
```

Phone model: Meizu S6
Android version: 7.0
Flyme version: 7.8.8.7 beta

**Comment by Piasy** [comment]
[In `GlideImageViewFactory.createThumbnailView`](https://github.com/Piasy/BigImageViewer/blob/master/GlideImageViewFactory/src/main/java/com/github/piasy/biv/view/GlideImageViewFactory.java#L64), it news an ImageView and use it, but the ImageView is null, I guess that's a sort of out-of-memory error?

Please do some debug on your device :)

**Comment by nukc** [comment]
并没有 OOM，Debug 之后发现是 scaleType 为空，ImageView 并没有问题，通过判断 null 值后，一切正常。https://github.com/Piasy/BigImageViewer/pull/130

**Comment by Piasy** [comment]
v1.5.6 fixed this issue.
