### ISSUE TITLE
NoClassDefFoundError, 求帮忙看下这个问题

### ISSUE THREAD

**Issue by Roben1016** [Piasy/BigImageViewer#147]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/github/piasy/biv/indicator/progresspie/R$layout;
        at com.github.piasy.biv.indicator.progresspie.ProgressPieIndicator.getView(ProgressPieIndicator.java:43)
        at com.github.piasy.biv.view.BigImageView$3.run(BigImageView.java:268)
        at android.os.Handler.handleCallback(Handler.java:891)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:7470)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)

求帮忙看下这个报错, 引用的是1.4.7版本, 谢谢了.

**Comment by Piasy** [comment]
能否提供一个可复现的 demo 项目？

**Comment by Roben1016** [comment]
@Piasy 目前已经换了实现方式, 但我猜测应该是我们项目老旧, 引用的第三方库比较多, 各种support-v4或者v7版本不统一导致的; 还是很感谢.
