### ISSUE TITLE
Glide error

### ISSUE THREAD

**Issue by hexlay** [Piasy/BigImageViewer#151]
```
com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.net.Uri$StringUri
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:576)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
```

Throws this error on image load without crashing app... 
I have removed original Glide i used in app and implemented

```
implementation 'com.github.piasy:BigImageViewer:1.5.7'
implementation 'com.github.piasy:GlideImageLoader:1.5.7'
```

**Comment by Piasy** [comment]
Could you please provide a demo project that could reproduce this problem?

**Comment by Piasy** [comment]
This maybe because the url is not HTTPS or something else. see #171

**Comment by ruben8888** [comment]
I have the same issue. When I set Uri from Internal storage, 
like this -> Uri(/data/user/0/com.app.example/files/simple.jpg) GlideImageLoader (on BigImageView) gives failure. 
But when the same patch without Uri , I set on Glide in my project it works great.
like this
  Glide
       .with(imageView.context)
       .load(/data/user/0/com.app.example/files/simple.jpg)  or        .load(File(/data/user/0/com.app.example/files/simple.jpg)) 
        .centerCrop()
        .into(imageView)
        
The problem is that , you only support Uri like this - >  ( showImage(Uri.parse(path)) ) 
Please can you fix this issue?
