### ISSUE TITLE
使用 Glide 无法加载本地图片

### ISSUE THREAD

**Issue by zhangls2014** [Piasy/BigImageViewer#160]
报错信息如下
`com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.net.Uri$StringUri
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:576)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)`

**Comment by Piasy** [comment]
给了权限没有？网络、外部存储之类。

**Comment by zhangls2014** [comment]
很抱歉打扰您，是我自己错误的使用了 `Uri.parse()` 方法造成了这个问题，不好意思

**Comment by yigepang** [comment]
这个问题是怎么解决的啊

**Comment by yigepang** [comment]
我也是同样的问题，不用Uri.parse()这个方法，那用什么方法呢，

**Comment by zhangls2014** [comment]
请检查你的 `Uri.parse()` 方法中传入的字符串是否符合 uri 结构
