### ISSUE TITLE
Use with dagger and glide

### ISSUE THREAD

**Issue by CarsonRedeye** [Piasy/BigImageViewer#164]
Do you have any suggestions for how to use this with dagger and glide? Currently I lazily initialize Glide via dagger, but when I try to initialize BigImageViewer via `BigImageViewer.initialize(GlideImageLoader.with(appContext));` i get a runtime exception because glide is being initialized twice or something

**Comment by Piasy** [comment]
Could you please provide the stack trace?

**Comment by CarsonRedeye** [comment]
Here it is. Actually I suspect it's something to do with dagger, but I'm really not sure what's going on.
```
2019-07-30 13:40:12.843 1012-1012/co.redeye.dms.dev E/AndroidRuntime: FATAL EXCEPTION: main
    Process: co.redeye.dms.dev, PID: 1012
    java.lang.RuntimeException: Unable to create application co.redeye.dms.application.App: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5876)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.IllegalStateException: GeneratedAppGlideModuleImpl is implemented incorrectly. If you've manually implemented this class, remove your implementation. The Annotation processor will generate a correct implementation.
        at com.bumptech.glide.Glide.throwIncorrectGlideModule(Glide.java:309)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:303)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:229)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223)
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184)
        at com.bumptech.glide.Glide.get(Glide.java:168)
        at com.github.piasy.biv.loader.glide.GlideImageLoader.<init>(GlideImageLoader.java:55)
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:64)
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:60)
        at co.redeye.dms.application.App.onCreate(App.kt:52)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:287)
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:229) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223) 
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184) 
        at com.bumptech.glide.Glide.get(Glide.java:168) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.<init>(GlideImageLoader.java:55) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:64) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:60) 
        at co.redeye.dms.application.App.onCreate(App.kt:52) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: kotlin.UninitializedPropertyAccessException: lateinit property appComponent has not been initialized
        at co.redeye.dms.application.App$Companion.getAppComponent(App.kt:42)
        at co.redeye.dms.application.GlideModule.<init>(GlideModule.kt:37)
        at com.bumptech.glide.GeneratedAppGlideModuleImpl.<init>(GeneratedAppGlideModuleImpl.java:18)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
        at com.bumptech.glide.Glide.getAnnotationGeneratedGlideModules(Glide.java:287) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:229) 
        at com.bumptech.glide.Glide.initializeGlide(Glide.java:223) 
        at com.bumptech.glide.Glide.checkAndInitializeGlide(Glide.java:184) 
        at com.bumptech.glide.Glide.get(Glide.java:168) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.<init>(GlideImageLoader.java:55) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:64) 
        at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:60) 
        at co.redeye.dms.application.App.onCreate(App.kt:52) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:199) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

**Comment by CarsonRedeye** [comment]
Wow I fixed it but just moving `BigImageViewer.initialize(GlideImageLoader.with(this))` below my appComponent initialization
