### ISSUE TITLE
Could you please provide a demo project that could reproduce this problem?

### ISSUE THREAD

**Issue by yigepang** [Piasy/BigImageViewer#170]
Could you please provide a demo project that could reproduce this problem?

_Originally posted by @Piasy in https://github.com/Piasy/BigImageViewer/issues/151#issuecomment-489603864_
我和他遇到相似的问题了，很恼火，不知什么情况

**Comment by yigepang** [comment]
请求博主解答，其实两年前就是这个问题，一直没有解决到，现在出现这个问题了，我粘贴一个图片http://xxsk.eksaas.com/Public/bookContent/b5a69fbcc64c3c248b3b7f61c69e696f/t13.jpg，你可以试试，具体报错如下：
2019-09-16 18:32:49.786 8252-8940/com.xtoucher.xingxingshikan E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.net.Uri$StringUri
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:576)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:784)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2019-09-16 18:32:49.876 1257-1830/? E/RMS.HwSysResManagerService: Process Permission error! pid:1984 uid:1001 Process.myPid:1257

**Comment by Piasy** [comment]
你在 demo 项目里调试调试呗，自己动手丰衣足食 :)

**Comment by Piasy** [comment]
你提供的 url 我这边可以正常加载。

**Comment by yigepang** [comment]
我这边用你的demo测试了，有相同问题，我已经提交新的问题，请确认
