### ISSUE TITLE
博主自己写的demo在部分版本手机无法加载图片，请确认

### ISSUE THREAD

**Issue by yigepang** [Piasy/BigImageViewer#171]
以下测试软件是博主**你写的demo**测试的，我分别采用**android studio自带模拟器**api21版本对应系统5.0系统和api28版本对应系统9.0系统，且同时通过进入**GlideLoaderActivity**中加载自带**唯一**大图图片
“http://youimg1.cctrip.com/target/tg/773/732/734/7ca19416b8cd423f8f6ef2d08366b7dc.jpg”结果如下：
望博主尽快用自己的demo测试这种情况
**安卓5.0**：加载正常
**安卓9.0**：无法加载且报错如下：
2019-09-16 19:26:38.847 15635-15675/com.github.piasy.biv.example E/GlideExecutor: Request threw uncaught throwable
    com.bumptech.glide.Registry$NoSourceEncoderAvailableException: Failed to find source encoder for data class: class android.net.Uri$StringUri
        at com.bumptech.glide.Registry.getSourceEncoder(Registry.java:576)
        at com.bumptech.glide.load.engine.DecodeHelper.getSourceEncoder(DecodeHelper.java:241)
        at com.bumptech.glide.load.engine.SourceGenerator.cacheData(SourceGenerator.java:75)
        at com.bumptech.glide.load.engine.SourceGenerator.startNext(SourceGenerator.java:46)
        at com.bumptech.glide.load.engine.DecodeJob.runGenerators(DecodeJob.java:309)
        at com.bumptech.glide.load.engine.DecodeJob.runWrapped(DecodeJob.java:279)
        at com.bumptech.glide.load.engine.DecodeJob.run(DecodeJob.java:235)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
        at com.bumptech.glide.load.engine.executor.GlideExecutor$DefaultThreadFactory$1.run(GlideExecutor.java:446)
2019-09-16 19:26:40.329 1858-2015/system_process E/TaskPersister: File error accessing recents directory (directory doesn't exist?).

**Comment by yigepang** [comment]
博主大大，麻烦尽快解决问题，找了各种资料据说是base64解码问题，但是不知从何下手

**Comment by yigepang** [comment]
我用的真机华为v10 9.0系统，出现的同样的问题，报同样的错误，为方便你测试，特意用了模拟器9.0测试是同样的问题

**Comment by yigepang** [comment]
找到原因了，9.0系统必须用https的网页链接，不然直接报错，我嘞个去，debug半天才发现，必须走https
