### ISSUE TITLE
android 10 保存图片失败，android 10会将图片mime type识别成/octet-stream，导致保存失败

### ISSUE THREAD

**Issue by crzaycat** [Piasy/BigImageViewer#183]
android 10 保存图片失败，android 10会将图片mime type识别成/octet-stream，导致保存失败
![errlog](https://user-images.githubusercontent.com/12668313/68444621-58c20a80-0212-11ea-8a9f-e02c32585c30.png)

图片测试地址:https://cdn.cfesport.com//attachment/2019/11/07eba2e80aae.com/large/pgc-image/3f23c2de986540609e9846f233c3ee23?imageView2/0/h/700/q/80

**Comment by Piasy** [comment]
PR is welcome!

**Comment by moodcal** [comment]
This issue has been fixed in the latest version(v1.6.5), but not completely:
contentValues.put(MediaStore.MediaColumns.DISPLAY_NAME, **_mCurrentImageFile.getName()_**); glide-cached file's name doesn't have "jpg" extension, This will cause the saved file not to be found in the system album. 
Suggest to check file extension before save. @Piasy

**Comment by Piasy** [comment]
I verified that it worked fine on Pixel, which device are you using?

**Comment by moodcal** [comment]
My device is HUAWEI P20 pro (Android 10),  the saved file (without .jpg extension)  can be found in file system, but not invisible in system Gallery, also can't be imported in app (e.g. WeChat). if the file is appended the ".jpg", everything is solved

**Comment by Piasy** [comment]
How about save a image in png or gif format? @moodcal

**Comment by moodcal** [comment]
I have tested a gif file on my device(P20Pro),  not working correctly(the saved file is treated as jpeg, no animation), so the format detection should be done before appending the extension.

**Comment by Piasy** [comment]
Yeah, that's true. It worked on Google Photos when I tested on Pixel, so I didn't add that logic. Looks like necessary now.

My idea is to parsing file header, but not sure if common formats has such header.

BTW, PR is welcome!

**Comment by moodcal** [comment]
A simple solution is to use the mUri's extension directly :-)

**Comment by Piasy** [comment]
That's very easy to break, many social media don't have extension in their image url.

**Comment by moodcal** [comment]
Yeah,  but it's understandable to keep the same extension as the original file

**Comment by gongshoudao** [comment]
java.lang.IllegalArgumentException: MIME type application/octet-stream cannot be inserted into content://media/external/images/media; expected MIME type under image/*
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
	at android.content.ContentProviderProxy.insert(ContentProviderNative.java:481)
	at android.content.ContentResolver.insert(ContentResolver.java:1828)
	at android.provider.MediaStore.createPending(MediaStore.java:616)
	at android.provider.MediaStore$Images$Media.insertImage(MediaStore.java:1736)
	at com.github.piasy.biv.view.BigImageView.saveImageIntoGallery(:2)

**Comment by gongshoudao** [comment]
`private String insertImage(String imagePath,
                               String name) throws Exception {
        final File file = new File(imagePath);
        final String mimeType = "image/jpeg";//determine mime type

        if (TextUtils.isEmpty(name)) name = "Image";
        Uri insertUri = MediaStore.Images.Media.EXTERNAL_CONTENT_URI;
        ContentValues contentValues = getContentValues(name, mimeType);

        Uri insert = getContext().getContentResolver().insert(insertUri, contentValues);

        try (InputStream in = new FileInputStream(file);
             OutputStream out = getContext().getContentResolver().openOutputStream(insert)) {
            FileUtils.copy(in, out);
            return publish(insertUri).toString();
        } catch (Exception e) {
            try {
                FirebaseCrashlytics.getInstance().recordException(e);
                getContext().getContentResolver().delete(insert, null, null);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            return null;
        }
    }

    private ContentValues getContentValues(String displayName, String mimeType) {
        final long now = System.currentTimeMillis() / 1000;
        ContentValues insertValues = new ContentValues();
        insertValues.put(MediaStore.MediaColumns.DISPLAY_NAME, Objects.requireNonNull(displayName));
        insertValues.put(MediaStore.MediaColumns.MIME_TYPE, Objects.requireNonNull(mimeType));
        insertValues.put(MediaStore.MediaColumns.DATE_ADDED, now);
        insertValues.put(MediaStore.MediaColumns.DATE_MODIFIED, now);
        insertValues.put(MediaStore.MediaColumns.IS_PENDING, 1);
        insertValues.put(MediaStore.MediaColumns.DATE_EXPIRES,
                (System.currentTimeMillis() + DateUtils.DAY_IN_MILLIS) / 1000);
        return insertValues;

    }

    private Uri publish(Uri insertUri) {
        final ContentValues values = new ContentValues();
        values.put(MediaStore.MediaColumns.IS_PENDING, 0);
        values.putNull(MediaStore.MediaColumns.DATE_EXPIRES);
        getContext().getContentResolver().update(insertUri, values, null, null);
        return insertUri;
    }`
