### ISSUE TITLE
saveImageIntoGallery not working on Android 11

### ISSUE THREAD

**Issue by dabutaizha** [Piasy/BigImageViewer#229]
Device: Redmi10x  Android11 (MIUI12.5.2) 

```
java.lang.IllegalArgumentException: Unsupported MIME type image/jpg
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:172)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:549)
        at android.content.ContentResolver.insert(ContentResolver.java:2174)
        at android.content.ContentResolver.insert(ContentResolver.java:2136)
        at com.github.piasy.biv.view.BigImageView.saveImageIntoGallery(BigImageView.java:335)
```

**Comment by Piasy** [comment]
PR is welcome!

**Comment by Piasy** [comment]
v1.8.1 is released, check it out.

**Comment by amentan** [comment]
Tips，Remember to add in app manifest.
  <queries>
        <intent>
            <action android:name="android.intent.action.SEND" />
            <data android:mimeType="image/jpeg" />
        </intent>
    </queries>
