### ISSUE TITLE
Error inflating class com.github.piasy.biv.view.BigImageView

### ISSUE THREAD

**Issue by yanchengdeng** [Piasy/BigImageViewer#23]
Caused by: android.view.InflateException: Binary XML file line #21: Binary XML file line #21: Error inflating class com.github.piasy.biv.view.BigImageView
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:539)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
                                                                   at android.view.LayoutInflater.inflate(LayoutInflater.java:374)

**Comment by yanchengdeng** [comment]
the package name is right!

**Comment by Piasy** [comment]
It should be an OOM.

**Comment by yanchengdeng** [comment]
so   how  to solve this problem!兄弟

**Comment by Piasy** [comment]
That's beyond the scope of this library, bro!

Although this library aim to avoid OOM when you displaying big images, but there are tons of places that would cause OOM. Sorry that I can't help out all of them :(

**Comment by yanchengdeng** [comment]
ok  ! I have to use another View to solve it ! thx!

**Comment by Piasy** [comment]
Hope you well :)
