### ISSUE TITLE
Crash on ProgressView

### ISSUE THREAD

**Issue by KevinYaoooooo** [Piasy/BigImageViewer#37]
03-04 19:23:06.687 16550-16550/com.pisces.xsplash.debug E/AndroidRuntime: FATAL EXCEPTION: main
                                                                          Process: com.pisces.xsplash.debug, PID: 16550
                                                                          java.lang.NullPointerException: Attempt to invoke virtual method 'void com.filippudak.ProgressPieView.ProgressPieView.setProgress(int)' on a null object reference
                                                                              at com.github.piasy.biv.indicator.progresspie.ProgressPieIndicator.onProgress(ProgressPieIndicator.java:58)
                                                                              at com.github.piasy.biv.view.BigImageView$1.run(BigImageView.java:84)
                                                                              at android.os.Handler.handleCallback(Handler.java:739)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:148)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by Piasy** [comment]
What's the situation when the crash happened?

**Comment by KevinYaoooooo** [comment]
like user is open the image viewer page, then quickly get back, crash just happened.

**Comment by Piasy** [comment]
Got it, so I think it's caused by #36.

**Comment by KevinYaoooooo** [comment]
yeah, right

**Comment by Yukooo** [comment]
In my case, it happens when I change screen orientation while a loading process is showing

**Comment by Piasy** [comment]
@Yukooo I see, I'll take a look into it today.
