### ISSUE TITLE
demo中的图可以显示，我随便找一张就不可以

### ISSUE THREAD

**Issue by chenwulue** [Piasy/BigImageViewer#59]
`
    Failed to initialise bitmap decoder
                             java.io.IOException: Image failed to decode using PNG decoder
                                 at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                 at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
                                 at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
                                 at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:62)
                                 at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1515)
                                 at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1490)
                                 at android.os.AsyncTask$2.call(AsyncTask.java:295)
                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                 at java.lang.Thread.run(Thread.java:818)
`

用的是
[ http://photo.weibo.com/1749127163/wbphotos/large/mid/4127938703768828/pid/68418ffbly1fheo5qvx7vj20u07h6u11](url)
 [http://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E9%95%BF&step_word=&hs=0&pn=35&spn=0&di=201017571590&pi=0&rn=1&tn=baiduimagedetail&is=0%2C0&istype=2&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=-1&cs=3544136352%2C3666326020&os=46646094%2C3418315924&simid=0%2C0&adpicid=0&lpn=0&ln=1593&fr=&fmq=1500552502786_R&fm=index&ic=0&s=undefined&se=&sme=&tab=0&width=&height=&face=undefined&ist=&jit=&cg=&bdtype=0&oriquery=&objurl=http%3A%2F%2Fww1.sinaimg.cn%2Flarge%2F005vbOHfgw1ex5g4nd1xqg30kk0c1u0y.gif&fromurl=ippr_z2C%24qAzdH3FAzdH3F3wg1wg_z%26e3BgjpAzdH3F55xxAzdH3Frw2j-8c0l&gsm=0&rpstart=0&rpnum=0](url)

**Comment by Piasy** [comment]
你用的 url，打开网页里面确实有图片，但它是图片的 url 么？...

**Comment by chenwulue** [comment]
直接打开是有问题的，你要复制之后再打开。。
确实是图片的url

**Comment by chenwulue** [comment]
好像是我的问题，原来微博图片的显示逻辑换了，抱歉，你关了这个issue吧，
