### ISSUE TITLE
  java.io.IOException: Image failed to decode using JPEG decoder

### ISSUE THREAD

**Issue by yigepang** [Piasy/BigImageViewer#60]
不知是怎么回事儿，viewpager中使用，部分图一直显示在百分之百进度，但是图片不能加载出来

**Comment by yigepang** [comment]
Failed to initialise bitmap decoder
                                                            java.io.IOException: Image failed to decode using JPEG decoder
                                                                at android.graphics.BitmapRegionDecoder.nativeNewInstance(Native Method)
                                                                at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:124)
                                                                at android.graphics.BitmapRegionDecoder.newInstance(BitmapRegionDecoder.java:150)
                                                                at com.davemorrissey.labs.subscaleview.decoder.SkiaImageRegionDecoder.init(SkiaImageRegionDecoder.java:62)
                                                                at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1515)
                                                                at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1490)
                                                                at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                at java.lang.Thread.run(Thread.java:818)

**Comment by Piasy** [comment]
麻烦贴一下 url，机型。

**Comment by yigepang** [comment]
http://xxsk.xtoucher.com/Public/bookContent/49b7abb7131ba726dd4b3a6446edfc43/t81.jpg
http://xxsk.xtoucher.com/Public/bookContent/49b7abb7131ba726dd4b3a6446edfc43/t83.jpg
http://xxsk.xtoucher.com/Public/bookContent/49b7abb7131ba726dd4b3a6446edfc43/t84.jpg
问题机型是MI 2SC,系统是5.0.2，华为荣耀7页会出现该问题，红米note4,6.0系统，未出现该问题，其他系统暂未知

**Comment by Piasy** [comment]
demo 的图片问题机型能否显示？

**Comment by yigepang** [comment]
demo能显示，但项目图片部分能显示，部分不能显示

**Comment by yigepang** [comment]
请问根据日志能否告知一下，大概是哪方面的问题？

**Comment by Piasy** [comment]
这个日志我之前在正常机型上也见过，未必是真正的问题。不过也有可能在部分机型上确实没有相应的 decoder。

我最近比较忙，可能没时间追查这个问题，你可以把这个图片存到手机本地，直接试试 SSIV 加载本地图片，如果 SSIV 也不行，那就不是 BIV 的问题了。

**Comment by Piasy** [comment]
Close this issue now, feel free to provide more information and reopen it.
