### ISSUE TITLE
  Caused by: android.view.InflateException:

### ISSUE THREAD

**Issue by yanxinmiao** [Piasy/BigImageViewer#61]
```
Caused by: android.view.InflateException: Binary XML file line #26: Binary XML file line #26: Error inflating class com.github.piasy.biv.view.BigImageView
         at android.view.LayoutInflater.inflate(LayoutInflater.java:543)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:427)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
   atandroid.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:292)
```
this is my code 
```
 <com.github.piasy.biv.view.BigImageView
            android:id="@+id/photo_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:failureImage="@drawable/default_entry_pic"
            app:failureImageInitScaleType="center"
            app:optimizeDisplay="false" />

@BindView(R.id.photo_view)
BigImageView mBigImage;
@Override
protected void onCreate(Bundle savedInstanceState) {
            BigImageViewer.initialize(GlideImageLoader.with(MyApplication.getApplication()));
            setContentview(R.layout.activiyt_main);
            mBigImage.showImage(Uri.parse(url));
}

```

**Comment by Piasy** [comment]
Does demo crash? Find out difference it demo doesn't crash.

**Comment by blink7** [comment]
In your activity write this line to initialize the Viewer:

`BigImageViewer.initialize(FrescoImageLoader.with(getApplicationContext()));`

**Comment by yanxinmiao** [comment]
加上  BigImageViewer.initialize(GlideImageLoader.with(MyApplication.getApplication())); ，还是报错 ，这个库支持Glide 4.0版本吗

```
FATAL EXCEPTION: main
                                                                       Process: com.hudong.baikejiemi, PID: 23390
                                                                       java.lang.NoSuchMethodError: No virtual method register(Ljava/lang/Class;Ljava/lang/Class;Lcom/bumptech/glide/load/model/ModelLoaderFactory;)V in class Lcom/bumptech/glide/Glide; or its super classes (declaration of 'com.bumptech.glide.Glide' appears in /data/app/com.hudong.baikejiemi-2/split_lib_dependencies_apk.apk:classes66.dex)
                                                                           at com.github.piasy.biv.loader.glide.GlideProgressSupport.init(GlideProgressSupport.java:76)
                                                                           at com.github.piasy.biv.loader.glide.GlideImageLoader.<init>(GlideImageLoader.java:50)
                                                                           at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:59)
                                                                           at com.github.piasy.biv.loader.glide.GlideImageLoader.with(GlideImageLoader.java:55)
```

**Comment by Piasy** [comment]
Close this issue now, feel free to provide more information and reopen it.

Besides, glide 4.x is supported since `v1.4.0`

**Comment by potter777** [comment]
i did this:

`BigImageViewer.initialize(GlideImageLoader.with(getApplicationContext()));
        ButterKnife.bind(this, mView);`

i think, you have get initialize before bind the view.

**Comment by potter777** [comment]
I had same issue. 
I solved it, Initializing BigImage before inflate the view (a fragment in my case).
